#!/usr/bin/env python3
"""Rebuild deterministic RFC 8945 vectors using Python's stdlib, not Rust code.

The secret b'test' and fixed timestamp are public test data. Run this file from
any directory; no network, third-party packages, or running server are needed.
"""
from pathlib import Path
import hashlib
import hmac
import struct

TIME = 1700000000
KEY = b'test'
ALGORITHMS = {
    'md5': 'hmac-md5.sig-alg.reg.int.',
    'sha1': 'hmac-sha1.', 'sha224': 'hmac-sha224.',
    'sha256': 'hmac-sha256.', 'sha384': 'hmac-sha384.', 'sha512': 'hmac-sha512.',
}


def u16(value):
    return struct.pack('!H', value)


def name(value):
    return b''.join(bytes([len(label)]) + label.encode('ascii') for label in value.rstrip('.').split('.')) + b'\x00'


def header(flags, zones=1, updates=0, additional=0):
    return struct.pack('!6H', 0x1234, flags, zones, 0, updates, additional)


ZONE = name('example.test.') + struct.pack('!HH', 6, 1)
UPDATE = name('host.example.test.') + struct.pack('!HHIH', 1, 1, 300, 4) + bytes([192, 0, 2, 1])
UNSIGNED_REQUEST = header(0x2800, updates=1) + ZONE + UPDATE


def sign(unsigned, algorithm, request_mac=None, *, time=TIME, error=0, other=b'',
         keyname='test-key.', algname=None, mac_size=None):
    key_name = name(keyname)
    alg_name = name(algname or ALGORITHMS[algorithm])
    timers = time.to_bytes(6, 'big') + u16(300)
    variables = key_name.lower() + struct.pack('!HI', 255, 0) + alg_name.lower() + timers + u16(error) + u16(len(other)) + other
    prefix = b'' if request_mac is None else u16(len(request_mac)) + request_mac
    mac = hmac.new(KEY, prefix + unsigned + variables, getattr(hashlib, algorithm)).digest()
    if mac_size is not None:
        mac = mac[:mac_size]
    rdata = alg_name + timers + u16(len(mac)) + mac + u16(0x1234) + u16(error) + u16(len(other)) + other
    arcount = int.from_bytes(unsigned[10:12], 'big') + 1
    signed = unsigned[:10] + u16(arcount) + unsigned[12:] + key_name + struct.pack('!HHIH', 250, 255, 0, len(rdata)) + rdata
    return signed, mac


def generate():
    vectors = {}
    for alg in ALGORITHMS:
        request, mac = sign(UNSIGNED_REQUEST, alg)
        vectors[f'{alg}-request'] = request
        vectors[f'{alg}-response'] = sign(header(0xa800) + ZONE, alg, mac)[0]
    mac = sign(UNSIGNED_REQUEST, 'sha256')[1]
    variants = {
        'refused': (header(0xa805) + ZONE, {}),
        'badtime': (header(0xa809) + ZONE, {'error': 18, 'other': (TIME + 3600).to_bytes(6, 'big')}),
        'badtrunc': (header(0xa809) + ZONE, {'error': 22}),
        'unsigned-badkey': (header(0xa809) + ZONE, {'error': 17, 'mac_size': 0}),
        'short-mac': (header(0xa800) + ZONE, {'mac_size': 16}),
        'tc': (header(0xaa00) + ZONE, {}),
        'no-zone': (header(0xa800, zones=0), {}),
        'wrong-zone': (header(0xa800) + name('other.test.') + struct.pack('!HH', 6, 1), {}),
        'mixed-case': (header(0xa800) + ZONE, {'keyname': 'TEST-KEY.', 'algname': 'HMAC-SHA256.'}),
        # The owner of this glue record is compressed to the zone at offset 12.
        'compressed-glue': (header(0xa800, additional=1) + ZONE + b'\x02ns\xc0\x0c' + struct.pack('!HHIH', 1, 1, 300, 4) + bytes([192, 0, 2, 53]), {}),
        'edns-error': (header(0xa800, additional=1) + ZONE + b'\x00' + struct.pack('!HHIH', 41, 1232, 1 << 24, 0), {}),
        'opaque-additional': (header(0xa800, additional=1) + ZONE + b'\x00' + struct.pack('!HHIH', 65280, 1, 0, 5) + b'\xc0\xff\x00\xfa\xff', {}),
    }
    for label, (unsigned, options) in variants.items():
        vectors[f'sha256-{label}'] = sign(unsigned, 'sha256', mac, **options)[0]
    return '# Generated by generate_tsig.py; key=test, id=0x1234, time=1700000000\n' + ''.join(f'{label} {packet.hex()}\n' for label, packet in vectors.items())


if __name__ == '__main__':
    Path(__file__).with_name('tsig.txt').write_text(generate())
